# Generated by Django 3.0.8 on 2020-07-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='url',
            field=models.TextField(default='None'),
        ),
    ]
